# Generated by Django 5.2.5 on 2025-08-15 00:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('rif', models.CharField(blank=True, max_length=20, verbose_name='R.I.F.')),
                ('direccion_fiscal', models.TextField(blank=True, verbose_name='Dirección Fiscal')),
                ('persona_contacto', models.CharField(blank=True, max_length=100, verbose_name='Persona Contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Contacto')),
                ('dia_cobro', models.PositiveIntegerField(default=1, verbose_name='Día de Cobro')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Plan')),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Por Cantidad de Servicios'), ('MONTO', 'Por Monto de Cobertura (USD)')], default='CANTIDAD', max_length=10, verbose_name='Tipo de Plan')),
                ('monto_cobertura_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto tope para planes por cobertura. Dejar en 0 si no aplica.', max_digits=12, verbose_name='Monto Cobertura (USD)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción General')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='R.I.F.')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('direccion_fiscal', models.TextField(verbose_name='Dirección Fiscal')),
                ('tipo_negociacion', models.CharField(choices=[('CONVENIO', 'Convenio'), ('PREPAGO', 'Prepago'), ('HORARIO', 'Horario Acordado')], default='CONVENIO', max_length=10, verbose_name='Tipo de Negociación')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True, verbose_name='Número de Contrato/Póliza')),
                ('aseguradora', models.CharField(blank=True, max_length=100, verbose_name='Aseguradora')),
                ('ente', models.CharField(blank=True, max_length=100, verbose_name='Ente')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ramo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLECTIVO', 'Colectivo')], default='COLECTIVO', max_length=10)),
                ('fraccionamiento', models.CharField(choices=[('ANUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('TRIMESTRAL', 'Trimestral'), ('MENSUAL', 'Mensual'), ('OTRO', 'Otro')], default='ANUAL', max_length=20)),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin_vigencia', models.DateField(verbose_name='Fecha Fin Vigencia')),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='gestion.plan')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAsegurado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'Pasaporte'), ('M', 'Menor (Sin C.I.)')], max_length=1)),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula/Documento')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('parentesco', models.CharField(choices=[('TITULAR', 'Titular'), ('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('OTRO', 'Otro')], max_length=10)),
                ('telefono_celular', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Celular')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('estado_residencia', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('ciudad_residencia', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('estado_individual', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo (Falta de Pago)'), ('DE_BAJA', 'De Baja')], default='ACTIVO', max_length=10, verbose_name='Estado Individual')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.contrato')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical asegurado',
                'verbose_name_plural': 'historical Asegurados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre_plan', models.CharField(db_index=True, max_length=100, verbose_name='Nombre del Plan')),
                ('tipo', models.CharField(choices=[('CANTIDAD', 'Por Cantidad de Servicios'), ('MONTO', 'Por Monto de Cobertura (USD)')], default='CANTIDAD', max_length=10, verbose_name='Tipo de Plan')),
                ('monto_cobertura_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto tope para planes por cobertura. Dejar en 0 si no aplica.', max_digits=12, verbose_name='Monto Cobertura (USD)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción General')),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical plan',
                'verbose_name_plural': 'historical Planes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProveedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rif', models.CharField(db_index=True, max_length=20, verbose_name='R.I.F.')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('direccion_fiscal', models.TextField(verbose_name='Dirección Fiscal')),
                ('tipo_negociacion', models.CharField(choices=[('CONVENIO', 'Convenio'), ('PREPAGO', 'Prepago'), ('HORARIO', 'Horario Acordado')], default='CONVENIO', max_length=10, verbose_name='Tipo de Negociación')),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical proveedor',
                'verbose_name_plural': 'historical Proveedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContrato',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_contrato', models.CharField(db_index=True, max_length=50, verbose_name='Número de Contrato/Póliza')),
                ('aseguradora', models.CharField(blank=True, max_length=100, verbose_name='Aseguradora')),
                ('ente', models.CharField(blank=True, max_length=100, verbose_name='Ente')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ramo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLECTIVO', 'Colectivo')], default='COLECTIVO', max_length=10)),
                ('fraccionamiento', models.CharField(choices=[('ANUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('TRIMESTRAL', 'Trimestral'), ('MENSUAL', 'Mensual'), ('OTRO', 'Otro')], default='ANUAL', max_length=20)),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio Vigencia')),
                ('fecha_fin_vigencia', models.DateField(verbose_name='Fecha Fin Vigencia')),
                ('activo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.plan')),
            ],
            options={
                'verbose_name': 'historical contrato',
                'verbose_name_plural': 'historical Contratos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CuentaBancariaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Corriente'), ('AHORROS', 'Ahorros'), ('ZELLE', 'Zelle'), ('PAYPAL', 'PayPal'), ('CUSTODIA', 'Cuenta Custodia'), ('PAGOMOVIL', 'Pago Móvil')], max_length=10, verbose_name='Tipo')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco / Plataforma')),
                ('numero_cuenta', models.CharField(max_length=100, verbose_name='Número de Cuenta / Correo / Teléfono')),
                ('titular', models.CharField(max_length=100, verbose_name='Nombre del Titular')),
                ('cedula_rif', models.CharField(max_length=20, verbose_name='Cédula o RIF del Titular')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='gestion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(max_length=255, verbose_name='Nombre de la Sede/APS')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('direccion', models.TextField(verbose_name='Dirección de la Sede')),
                ('telefonos', models.CharField(max_length=150, verbose_name='Teléfonos de Contacto')),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_atencion', to='gestion.proveedor')),
            ],
            options={
                'verbose_name': 'Punto de Atención',
                'verbose_name_plural': 'Puntos de Atención',
            },
        ),
        migrations.CreateModel(
            name='SubServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del Sub-Servicio')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservicios', to='gestion.categoriaservicio')),
            ],
            options={
                'verbose_name': 'Sub Servicio',
                'verbose_name_plural': 'Sub Servicios',
            },
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'Pasaporte'), ('M', 'Menor (Sin C.I.)')], max_length=1)),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula/Documento')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('parentesco', models.CharField(choices=[('TITULAR', 'Titular'), ('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('OTRO', 'Otro')], max_length=10)),
                ('telefono_celular', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Celular')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('estado_residencia', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('ciudad_residencia', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('estado_individual', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo (Falta de Pago)'), ('DE_BAJA', 'De Baja')], default='ACTIVO', max_length=10, verbose_name='Estado Individual')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asegurados', to='gestion.contrato')),
            ],
            options={
                'verbose_name_plural': 'Asegurados',
                'unique_together': {('contrato', 'cedula')},
            },
        ),
        migrations.CreateModel(
            name='CoberturaCategoriaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_ilimitada', models.BooleanField(default=False, help_text='Marcar si la cobertura para esta categoría es ilimitada.', verbose_name='Cobertura Ilimitada')),
                ('cantidad_maxima', models.PositiveIntegerField(default=0, help_text='Dejar en 0 si la cobertura es ilimitada.', verbose_name='Cantidad Máxima Anual')),
                ('limite_mensual', models.PositiveIntegerField(default=0, help_text='Dejar en 0 si no hay límite mensual.', verbose_name='Límite Mensual')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categoriaservicio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_categoria', to='gestion.plan')),
            ],
            options={
                'verbose_name': 'Cobertura por Tipo Plan',
                'verbose_name_plural': 'Coberturas por Tipo Plan',
                'unique_together': {('plan', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='DetallePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.plan')),
                ('sub_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.subservicio')),
            ],
            options={
                'verbose_name': 'Detalle de Plan',
                'verbose_name_plural': 'Detalles de Planes',
                'unique_together': {('plan', 'sub_servicio')},
            },
        ),
        migrations.CreateModel(
            name='BaremoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (USD)')),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baremo', to='gestion.proveedor')),
                ('sub_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_asociados', to='gestion.subservicio')),
            ],
            options={
                'verbose_name': 'Baremo de Proveedor',
                'verbose_name_plural': 'Baremo Proveedores',
                'unique_together': {('proveedor', 'sub_servicio')},
            },
        ),
    ]
