# Generated by Django 5.2.5 on 2025-08-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoatencion',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Municipio'),
        ),
    ]
