# Generated by Django 5.2.5 on 2025-08-15 00:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Reporte')),
                ('descripcion_siniestro', models.TextField(verbose_name='Descripción del Siniestro')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado con OS'), ('IMPROCEDENTE', 'Improcedente')], default='ABIERTO', max_length=20, verbose_name='Estado del Siniestro')),
                ('asegurado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='gestion.asegurado')),
            ],
            options={
                'verbose_name_plural': 'Siniestros',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSiniestro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Reporte')),
                ('descripcion_siniestro', models.TextField(verbose_name='Descripción del Siniestro')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado con OS'), ('IMPROCEDENTE', 'Improcedente')], default='ABIERTO', max_length=20, verbose_name='Estado del Siniestro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asegurado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.asegurado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical siniestro',
                'verbose_name_plural': 'historical Siniestros',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrdenDeServicio',
            fields=[
                ('numero_os', models.CharField(blank=True, db_index=True, editable=False, max_length=50, verbose_name='Número de OS')),
                ('monto_referencial_os', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Referencial OS (USD)')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento_activacion', models.DateField(blank=True, editable=False, null=True, verbose_name='Vencimiento para Activación')),
                ('detalle_estudio', models.TextField(blank=True, verbose_name='Detalle de la Consulta o Estudio')),
                ('estado_os', models.CharField(choices=[('AUT', 'Pendiente de Autorización'), ('NOT', 'Notificada'), ('ACT', 'Activada'), ('SUS', 'Suspendida (Vencida)'), ('PEN', 'Pendiente por Pagar'), ('PAG', 'Pagada'), ('REC', 'Rechazada')], default='AUT', max_length=3, verbose_name='Estado de la OS')),
                ('fecha_auditoria', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoría')),
                ('es_exonerada', models.BooleanField(default=False, verbose_name='Exonerada (Presidencia)')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('numero_control_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control')),
                ('fecha_emision_factura', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión Factura')),
                ('fecha_recepcion_factura', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción Factura')),
                ('monto_factura_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Factura (VES)')),
                ('monto_factura_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Factura (USD)')),
                ('tasa_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tasa BCV')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('auditado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor que auditó la OS.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('punto_atencion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gestion.puntoatencion')),
                ('siniestro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operaciones.siniestro')),
            ],
            options={
                'verbose_name': 'historical Orden de Servicio',
                'verbose_name_plural': 'historical Órdenes de Servicio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrdenDeServicio',
            fields=[
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='operaciones.siniestro')),
                ('numero_os', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Número de OS')),
                ('monto_referencial_os', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Referencial OS (USD)')),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento_activacion', models.DateField(blank=True, editable=False, null=True, verbose_name='Vencimiento para Activación')),
                ('detalle_estudio', models.TextField(blank=True, verbose_name='Detalle de la Consulta o Estudio')),
                ('estado_os', models.CharField(choices=[('AUT', 'Pendiente de Autorización'), ('NOT', 'Notificada'), ('ACT', 'Activada'), ('SUS', 'Suspendida (Vencida)'), ('PEN', 'Pendiente por Pagar'), ('PAG', 'Pagada'), ('REC', 'Rechazada')], default='AUT', max_length=3, verbose_name='Estado de la OS')),
                ('fecha_auditoria', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoría')),
                ('es_exonerada', models.BooleanField(default=False, verbose_name='Exonerada (Presidencia)')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('motivo_rechazo', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura')),
                ('numero_control_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control')),
                ('fecha_emision_factura', models.DateField(blank=True, null=True, verbose_name='Fecha Emisión Factura')),
                ('fecha_recepcion_factura', models.DateField(blank=True, null=True, verbose_name='Fecha Recepción Factura')),
                ('monto_factura_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Factura (VES)')),
                ('monto_factura_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Factura (USD)')),
                ('tasa_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tasa BCV')),
                ('auditado_por', models.ForeignKey(blank=True, help_text='Supervisor que auditó la OS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_auditadas', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('punto_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.puntoatencion')),
                ('servicios_prestados', models.ManyToManyField(to='gestion.baremoproveedor')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
            },
        ),
    ]
