# Generated by Django 5.2.5 on 2025-08-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordendeservicio',
            name='detalle_estudio',
            field=models.TextField(blank=True, verbose_name='Detalle de la Consulta o Estudio'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='detalle_estudio',
            field=models.TextField(blank=True, verbose_name='Detalle de la Consulta o Estudio'),
        ),
    ]
