# Generated by Django 5.2.5 on 2025-08-13 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_historicalordendeservicio_detalle_estudio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordendeservicio',
            name='auditado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor que auditó la OS.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalordendeservicio',
            name='fecha_auditoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoría'),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='auditado_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que auditó la OS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_auditadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordendeservicio',
            name='fecha_auditoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoría'),
        ),
    ]
